In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('phishing.csv')
data.head(60)

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.000000,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.000000,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.000000,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.000000,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.000000,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1
5,23107.txt,https://www.globalreporting.org,30,www.globalreporting.org,23,0,org,100.000000,1.000000,0.079963,...,0,0,1,35,1,11,86,0,14,1
6,23034.txt,https://www.saffronart.com,25,www.saffronart.com,18,0,com,100.000000,1.000000,0.522907,...,0,0,1,32,4,14,44,2,17,1
7,696732.txt,https://www.nerdscandy.com,25,www.nerdscandy.com,18,0,com,100.000000,1.000000,0.522907,...,0,0,1,24,2,22,36,0,15,1
8,739255.txt,https://www.hyderabadonline.in,29,www.hyderabadonline.in,22,0,in,100.000000,1.000000,0.005084,...,0,0,1,71,4,9,40,1,317,1
9,14486.txt,https://www.aap.org,18,www.aap.org,11,0,org,100.000000,1.000000,0.079963,...,0,0,1,10,1,12,173,6,65,1
10,167350.txt,https://www.religionenlibertad.com,33,www.religionenlibertad.com,26,0,com,100.000000,1.000000,0.522907,...,1,0,1,80,13,10,376,1,9,1
11,mw42508.txt,http://www.teramill.com,22,www.teramill.com,16,0,com,82.644628,1.000000,0.522907,...,0,0,0,0,0,0,0,0,1,0
12,515489.txt,https://www.socialpolicy.org,27,www.socialpolicy.org,20,0,org,100.000000,1.000000,0.079963,...,0,0,1,16,9,13,92,1,18,1
13,858208.txt,https://www.aoh61.com,20,www.aoh61.com,13,0,com,100.000000,1.000000,0.522907,...,0,0,0,16,4,7,4,0,14,1
14,712305.txt,https://www.bulgariaski.com,26,www.bulgariaski.com,19,0,com,100.000000,1.000000,0.522907,...,1,0,1,63,12,22,156,2,184,1
15,252332.txt,https://www.brightika.com,24,www.brightika.com,17,0,com,100.000000,1.000000,0.522907,...,0,0,1,12,14,19,2,1,14,1
16,862789.txt,https://www.motley.ie,20,www.motley.ie,13,0,ie,100.000000,1.000000,0.001588,...,0,0,1,56,10,16,235,0,254,1
17,561324.txt,https://www.funzine.hu,21,www.funzine.hu,14,0,hu,100.000000,1.000000,0.002217,...,0,0,1,52,10,27,0,1,143,1
18,791831.txt,https://www.dixxon.com,21,www.dixxon.com,14,0,com,100.000000,1.000000,0.522907,...,1,0,1,259,14,33,168,1,90,1
19,861208.txt,https://www.ooty.ind.in,22,www.ooty.ind.in,15,0,in,100.000000,0.625000,0.005084,...,1,0,0,21,0,2,2,0,1,1
20,mw16985.txt,http://www.f0519141.xsph.ru,26,www.f0519141.xsph.ru,20,0,ru,55.284926,0.923077,0.018013,...,0,0,0,0,0,0,0,0,0,0
21,mw131249.txt,http://www.shprakserf.gq,24,www.shprakserf.gq,17,0,gq,56.551141,1.000000,0.000053,...,0,0,0,0,0,0,0,0,0,0
22,6569.txt,https://www.cryptocompare.com,28,www.cryptocompare.com,21,0,com,100.000000,1.000000,0.522907,...,1,1,1,49,2,4,111,2,39,1
23,394270.txt,https://www.diariodealmeria.es,29,www.diariodealmeria.es,22,0,es,100.000000,1.000000,0.006411,...,0,0,1,217,4,10,609,12,93,1
24,518245.txt,https://www.town.minamichita.lg.jp,33,www.town.minamichita.lg.jp,26,0,jp,100.000000,0.631579,0.023045,...,0,0,1,37,10,21,2,0,7,1
25,683655.txt,https://www.bwresearch.com,25,www.bwresearch.com,18,0,com,100.000000,1.000000,0.522907,...,0,0,1,14,2,4,2,2,4,1
26,638225.txt,https://www.musicvideoproduction.guru,36,www.musicvideoproduction.guru,29,0,guru,100.000000,1.000000,0.000095,...,1,0,1,10,3,6,23,2,17,1
27,7972389.txt,https://service-mitld.firebaseapp.com/,37,service-mitld.firebaseapp.com,29,0,com,64.645264,0.480000,0.522907,...,0,0,0,0,0,0,0,0,0,0
28,mw34096.txt,http://www.kuradox92.lima-city.de,32,www.kuradox92.lima-city.de,26,0,de,45.849802,0.526316,0.032650,...,0,0,0,1,0,0,1,0,1,0
29,8008520.txt,https://liuy-9a930.web.app/,26,liuy-9a930.web.app,18,0,app,54.515919,0.571429,0.001502,...,0,0,0,0,0,0,0,0,3,0
30,86745.txt,https://www.landed.com,21,www.landed.com,14,0,com,100.000000,1.000000,0.522907,...,1,0,1,13,17,29,45,1,59,1
31,8029912.txt,https://ipfs.io/ipfs/qmrvvyr84esa2assw9vvwupqj...,91,ipfs.io,7,0,io,9.669201,1.000000,0.012927,...,0,0,0,0,5,6,0,0,2,0
32,8066660.txt,http://att-103731-107123.weeblysite.com/,40,att-103731-107123.weeblysite.com,32,0,com,36.612216,0.607143,0.522907,...,0,0,0,0,0,0,1,0,1,0
33,53440.txt,https://www.bikeseoul.com,24,www.bikeseoul.com,17,0,com,100.000000,1.000000,0.522907,...,0,0,1,15,29,17,49,0,13,1
34,8065475.txt,https://hidok4f8zl.firebaseapp.com/,35,hidok4f8zl.firebaseapp.com,26,0,com,63.905325,0.590909,0.522907,...,0,0,0,0,0,0,0,0,3,0
35,584755.txt,https://www.ibeani.co.uk,23,www.ibeani.co.uk,16,0,uk,100.000000,0.777778,0.028555,...,1,0,1,64,69,20,137,0,23,1
36,603823.txt,https://www.metroretrovintage.com,32,www.metroretrovintage.com,25,0,com,100.000000,1.000000,0.522907,...,1,0,1,85,3,20,93,0,9,1
37,mw52024.txt,http://www.ooguy.com,19,www.ooguy.com,13,0,com,79.259259,1.000000,0.522907,...,0,0,0,0,0,0,1,0,1,0
38,62523.txt,https://www.vysor.io,19,www.vysor.io,12,0,io,100.000000,1.000000,0.012927,...,0,0,1,3,4,8,7,0,4,1
39,mw74078.txt,http://www.fairytalesinc.com,27,www.fairytalesinc.com,21,0,com,76.654412,1.000000,0.522907,...,0,0,0,0,0,1,1,0,1,0
40,mw65785.txt,http://www.iuhjn.pplink.club,27,www.iuhjn.pplink.club,21,0,club,47.366398,0.583333,0.000623,...,0,0,0,0,0,0,0,0,0,0
41,7932715.txt,https://mechinchem-5cb8a.web.app/,32,mechinchem-5cb8a.web.app,24,0,app,49.277778,0.600000,0.001502,...,0,0,0,0,1,1,1,0,1,0
42,532746.txt,https://www.salutlive.com,24,www.salutlive.com,17,0,com,100.000000,1.000000,0.522907,...,1,0,0,2,11,24,266,0,369,1
43,751473.txt,https://www.recettessimples.fr,29,www.recettessimples.fr,22,0,fr,100.000000,1.000000,0.014148,...,0,0,1,56,1,18,71,0,283,1
44,8016956.txt,https://fb-restriction-case-97be5.web.app/,41,fb-restriction-case-97be5.web.app,33,0,app,34.327230,0.482759,0.001502,...,0,0,0,0,0,0,0,0,3,0
45,8044158.txt,https://pontosapontamentolu.com/gclid/=/c/?gcl...,140,pontosapontamentolu.com,23,0,com,9.203795,1.000000,0.522907,...,0,0,0,0,0,0,0,0,0,0
46,386777.txt,https://www.ainewsletter.com,27,www.ainewsletter.com,20,0,com,100.000000,1.000000,0.522907,...,0,0,1,1,1,1,21,1,21,1
47,445249.txt,https://www.marrugeku.com.au,27,www.marrugeku.com.au,20,0,au,100.000000,0.769231,0.010086,...,1,0,1,9,10,20,83,0,84,1
48,527611.txt,https://www.sweatdrop.com,24,www.sweatdrop.com,17,0,com,100.000000,1.000000,0.522907,...,0,0,1,23,1,5,39,0,12,1
49,mw1796.txt,http://www.komaru.today,22,www.komaru.today,16,0,today,65.840220,1.000000,0.000160,...,0,0,0,0,0,0,0,0,0,0
50,8030239.txt,https://dev-634536.pantheonsite.io/,34,dev-634536.pantheonsite.io,26,0,io,76.134122,0.826087,0.012927,...,0,0,0,4,0,0,0,0,3,0
51,96527.txt,https://www.senacases.com,24,www.senacases.com,17,0,com,100.000000,1.000000,0.522907,...,1,0,1,42,26,53,139,3,40,1
52,8050920.txt,https://sabadonoappmagazine.com/,32,sabadonoappmagazine.com,23,0,com,64.429742,1.000000,0.522907,...,0,0,0,0,0,0,0,0,0,0
53,626639.txt,https://www.vespatales.com,25,www.vespatales.com,18,0,com,100.000000,1.000000,0.522907,...,0,0,0,180,3,7,260,0,124,1
54,mw27703.txt,http://www.nextraload.com,24,www.nextraload.com,18,0,com,72.108844,1.000000,0.522907,...,0,0,0,0,0,0,0,0,0,0
55,145087.txt,https://www.klerk.ru,19,www.klerk.ru,12,0,ru,100.000000,1.000000,0.018013,...,1,0,0,15,4,8,142,1,91,1
56,28887.txt,https://www.karenmillen.com,26,www.karenmillen.com,19,0,com,100.000000,1.000000,0.522907,...,1,1,1,3,8,50,403,2,417,1
57,8024229.txt,https://topaka.cloud/ob52gtplj/18snwp,36,topaka.cloud,12,0,cloud,32.017440,1.000000,0.000182,...,0,0,0,0,2,0,2,0,2,0
58,404766.txt,https://www.mlpack.org,21,www.mlpack.org,14,0,org,100.000000,1.000000,0.079963,...,1,0,1,1,1,3,1,0,10,1
59,8017962.txt,https://metafb-tvz6efk.web.app/,30,metafb-tvz6efk.web.app,22,0,app,51.953371,0.444444,0.001502,...,0,0,0,0,0,2,0,0,1,0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 56 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   FILENAME                    235795 non-null  object
 1   URL                         235795 non-null  object
 2   URLLength                   235795 non-null  int64
 3   Domain                      235795 non-null  object
 4   DomainLength                235795 non-null  int64
 5   IsDomainIP                  235795 non-null  int64
 6   TLD                         235795 non-null  object
 7   URLSimilarityIndex          235795 non-null  float64
 8   CharContinuationRate        235795 non-null  float64
 9   TLDLegitimateProb           235795 non-null  float64
 10  URLCharProb                 235795 non-null  float64
 11  TLDLength                   235795 non-null  int64
 12  NoOfSubDomain               235795 non-null  int64
 13  HasObfuscation              235795 non-null  int64
 14  NoOfObfuscatedChar          235795 non-null  int64
 15  ObfuscationRatio            235795 non-null  float64
 16  NoOfLettersInURL            235795 non-null  int64
 17  LetterRatioInURL            235795 non-null  float64
 18  NoOfDegitsInURL             235795 non-null  int64
 19  DegitRatioInURL             235795 non-null  float64
 20  NoOfEqualsInURL             235795 non-null  int64
 21  NoOfQMarkInURL              235795 non-null  int64
 22  NoOfAmpersandInURL          235795 non-null  int64
 23  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 24  SpacialCharRatioInURL       235795 non-null  float64
 25  IsHTTPS                     235795 non-null  int64
 26  LineOfCode                  235795 non-null  int64
 27  LargestLineLength           235795 non-null  int64
 28  HasTitle                    235795 non-null  int64
 29  Title                       235795 non-null  object
 30  DomainTitleMatchScore       235795 non-null  float64
 31  URLTitleMatchScore          235795 non-null  float64
 32  HasFavicon                  235795 non-null  int64
 33  Robots                      235795 non-null  int64
 34  IsResponsive                235795 non-null  int64
 35  NoOfURLRedirect             235795 non-null  int64
 36  NoOfSelfRedirect            235795 non-null  int64
 37  HasDescription              235795 non-null  int64
 38  NoOfPopup                   235795 non-null  int64
 39  NoOfiFrame                  235795 non-null  int64
 40  HasExternalFormSubmit       235795 non-null  int64
 41  HasSocialNet                235795 non-null  int64
 42  HasSubmitButton             235795 non-null  int64
 43  HasHiddenFields             235795 non-null  int64
 44  HasPasswordField            235795 non-null  int64
 45  Bank                        235795 non-null  int64
 46  Pay                         235795 non-null  int64
 47  Crypto                      235795 non-null  int64
 48  HasCopyrightInfo            235795 non-null  int64
 49  NoOfImage                   235795 non-null  int64
 50  NoOfCSS                     235795 non-null  int64
 51  NoOfJS                      235795 non-null  int64
 52  NoOfSelfRef                 235795 non-null  int64
 53  NoOfEmptyRef                235795 non-null  int64
 54  NoOfExternalRef             235795 non-null  int64
 55  label                       235795 non-null  int64
dtypes: float64(10), int64(41), object(5)
memory usage: 100.7+ MB

In [4]:
data.isnull().sum()

FILENAME                      0
URL                           0
URLLength                     0
Domain                        0
DomainLength                  0
IsDomainIP                    0
TLD                           0
URLSimilarityIndex            0
CharContinuationRate          0
TLDLegitimateProb             0
URLCharProb                   0
TLDLength                     0
NoOfSubDomain                 0
HasObfuscation                0
NoOfObfuscatedChar            0
ObfuscationRatio              0
NoOfLettersInURL              0
LetterRatioInURL              0
NoOfDegitsInURL               0
DegitRatioInURL               0
NoOfEqualsInURL               0
NoOfQMarkInURL                0
NoOfAmpersandInURL            0
NoOfOtherSpecialCharsInURL    0
SpacialCharRatioInURL         0
IsHTTPS                       0
LineOfCode                    0
LargestLineLength             0
HasTitle                      0
Title                         0
DomainTitleMatchScore         0
URLTitleMatchScore            0
HasFavicon                    0
Robots                        0
IsResponsive                  0
NoOfURLRedirect               0
NoOfSelfRedirect              0
HasDescription                0
NoOfPopup                     0
NoOfiFrame                    0
HasExternalFormSubmit         0
HasSocialNet                  0
HasSubmitButton               0
HasHiddenFields               0
HasPasswordField              0
Bank                          0
Pay                           0
Crypto                        0
HasCopyrightInfo              0
NoOfImage                     0
NoOfCSS                       0
NoOfJS                        0
NoOfSelfRef                   0
NoOfEmptyRef                  0
NoOfExternalRef               0
label                         0
dtype: int64

In [5]:
data.shape

(235795, 56)

In [6]:
data.describe()

,URLLength,DomainLength,IsDomainIP,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
count,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,...,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000,235795.000000
mean,34.573095,21.470396,0.002706,78.430778,0.845508,0.260423,0.055747,2.764456,1.164758,0.002057,...,0.237007,0.023474,0.486775,26.075689,6.333111,10.522305,65.071113,2.377629,49.262516,0.571895
std,41.314153,9.150793,0.051946,28.976055,0.216632,0.251628,0.010587,0.599739,0.600969,0.045306,...,0.425247,0.151403,0.499826,79.411815,74.866296,22.312192,176.687539,17.641097,161.027430,0.494805
min,13.000000,4.000000,0.000000,0.155574,0.000000,0.000000,0.001083,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,16.000000,0.000000,57.024793,0.680000,0.005977,0.050747,2.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,27.000000,20.000000,0.000000,100.000000,1.000000,0.079963,0.057970,3.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,8.000000,2.000000,6.000000,12.000000,0.000000,10.000000,1.000000
75%,34.000000,24.000000,0.000000,100.000000,1.000000,0.522907,0.062875,3.000000,1.000000,0.000000,...,0.000000,0.000000,1.000000,29.000000,8.000000,15.000000,88.000000,1.000000,57.000000,1.000000
max,6097.000000,110.000000,1.000000,100.000000,1.000000,0.522907,0.090824,13.000000,10.000000,1.000000,...,1.000000,1.000000,1.000000,8956.000000,35820.000000,6957.000000,27397.000000,4887.000000,27516.000000,1.000000

In [7]:
URL_ONLY_FEATURES = [
    "URLLength",
    "DomainLength",
    "IsDomainIP",
    "TLDLength",
    "NoOfSubDomain",
    "HasObfuscation",
    "NoOfObfuscatedChar",
    "ObfuscationRatio",
    "NoOfLettersInURL",
    "LetterRatioInURL",
    "NoOfDegitsInURL",
    "DegitRatioInURL",
    "NoOfEqualsInURL",
    "NoOfQMarkInURL",
    "NoOfAmpersandInURL",
    "NoOfOtherSpecialCharsInURL",
    "SpacialCharRatioInURL",
    "IsHTTPS",
]

In [8]:
# Drop rows where target variable 'label' is missing
cleaned_data = data.dropna(subset=['label'])

# Split into features (X) and target (y)
X = cleaned_data[URL_ONLY_FEATURES].astype(float).fillna(0)  # Filling any remaining missing feature values with 0
y = cleaned_data['label']

print(f"Features shape (X): {X.shape}")
print(f"Target shape (y): {y.shape}")
display(X.head())

Features shape (X): (235795, 18)
Target shape (y): (235795,)

,URLLength,DomainLength,IsDomainIP,TLDLength,NoOfSubDomain,HasObfuscation,NoOfObfuscatedChar,ObfuscationRatio,NoOfLettersInURL,LetterRatioInURL,NoOfDegitsInURL,DegitRatioInURL,NoOfEqualsInURL,NoOfQMarkInURL,NoOfAmpersandInURL,NoOfOtherSpecialCharsInURL,SpacialCharRatioInURL,IsHTTPS
0,31.0,24.0,0.0,3.0,1.0,0.0,0.0,0.0,18.0,0.581,0.0,0.0,0.0,0.0,0.0,1.0,0.032,1.0
1,23.0,16.0,0.0,2.0,1.0,0.0,0.0,0.0,9.0,0.391,0.0,0.0,0.0,0.0,0.0,2.0,0.087,1.0
2,29.0,22.0,0.0,2.0,2.0,0.0,0.0,0.0,15.0,0.517,0.0,0.0,0.0,0.0,0.0,2.0,0.069,1.0
3,26.0,19.0,0.0,3.0,1.0,0.0,0.0,0.0,13.0,0.500,0.0,0.0,0.0,0.0,0.0,1.0,0.038,1.0
4,33.0,26.0,0.0,3.0,1.0,0.0,0.0,0.0,20.0,0.606,0.0,0.0,0.0,0.0,0.0,1.0,0.030,1.0

In [9]:
print(X)

        URLLength  DomainLength  IsDomainIP  TLDLength  NoOfSubDomain  \
0            31.0          24.0         0.0        3.0            1.0
1            23.0          16.0         0.0        2.0            1.0
2            29.0          22.0         0.0        2.0            2.0
3            26.0          19.0         0.0        3.0            1.0
4            33.0          26.0         0.0        3.0            1.0
...           ...           ...         ...        ...            ...
235790       29.0          22.0         0.0        3.0            1.0
235791       28.0          21.0         0.0        2.0            2.0
235792       30.0          23.0         0.0        2.0            1.0
235793       55.0          47.0         0.0        3.0            2.0
235794       33.0          26.0         0.0        3.0            1.0

        HasObfuscation  NoOfObfuscatedChar  ObfuscationRatio  \
0                  0.0                 0.0               0.0
1                  0.0                 0.0               0.0
2                  0.0                 0.0               0.0
3                  0.0                 0.0               0.0
4                  0.0                 0.0               0.0
...                ...                 ...               ...
235790             0.0                 0.0               0.0
235791             0.0                 0.0               0.0
235792             0.0                 0.0               0.0
235793             0.0                 0.0               0.0
235794             0.0                 0.0               0.0

        NoOfLettersInURL  LetterRatioInURL  NoOfDegitsInURL  DegitRatioInURL  \
0                   18.0             0.581              0.0            0.000
1                    9.0             0.391              0.0            0.000
2                   15.0             0.517              0.0            0.000
3                   13.0             0.500              0.0            0.000
4                   20.0             0.606              0.0            0.000
...                  ...               ...              ...              ...
235790              16.0             0.552              0.0            0.000
235791              14.0             0.500              0.0            0.000
235792              17.0             0.567              0.0            0.000
235793              39.0             0.709              3.0            0.055
235794              20.0             0.606              0.0            0.000

        NoOfEqualsInURL  NoOfQMarkInURL  NoOfAmpersandInURL  \
0                   0.0             0.0                 0.0
1                   0.0             0.0                 0.0
2                   0.0             0.0                 0.0
3                   0.0             0.0                 0.0
4                   0.0             0.0                 0.0
...                 ...             ...                 ...
235790              0.0             0.0                 0.0
235791              0.0             0.0                 0.0
235792              0.0             0.0                 0.0
235793              0.0             0.0                 0.0
235794              0.0             0.0                 0.0

        NoOfOtherSpecialCharsInURL  SpacialCharRatioInURL  IsHTTPS
0                              1.0                  0.032      1.0
1                              2.0                  0.087      1.0
2                              2.0                  0.069      1.0
3                              1.0                  0.038      1.0
4                              1.0                  0.030      1.0
...                            ...                    ...      ...
235790                         1.0                  0.034      1.0
235791                         2.0                  0.071      1.0
235792                         1.0                  0.033      1.0
235793                         5.0                  0.091      1.0
235794                         1.0                  0.030      1.0

[235795 rows x 18 columns]

In [10]:
print(y)

0         1
1         1
2         1
3         1
4         1
         ..
235790    1
235791    1
235792    1
235793    0
235794    1
Name: label, Length: 235795, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [12]:
from sklearn.svm import LinearSVC
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

dataPipelineSVM = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('std_scaler', StandardScaler()),
    ('classifier', LinearSVC(max_iter=20000, C=0.1, random_state=42, dual="auto"))
])

In [13]:
dataPipelineSVM.fit(X_train, y_train)

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('std_scaler', StandardScaler()),
                ('classifier',
                 LinearSVC(C=0.1, max_iter=20000, random_state=42))])

In [14]:
y_pred_svm = dataPipelineSVM.predict(X_test)
print("pred distribution:", pd.Series(y_pred_svm).value_counts().to_dict())

pred distribution: {1: 27144, 0: 20015}

In [15]:
from sklearn.metrics import accuracy_score
train_accuracy_svm = accuracy_score(y_train, dataPipelineSVM.predict(X_train))
print(f"Model Accuracy on Training Data: {train_accuracy_svm:.6f}")

Model Accuracy on Training Data: 0.996326

In [16]:
test_accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"Model Accuracy on Unseen Data: {test_accuracy_svm:.6f}")

Model Accuracy on Unseen Data: 0.996310

In [17]:
from sklearn.model_selection import cross_val_score
cv_scores_svm = cross_val_score(
dataPipelineSVM,
X_train,
y_train,
cv=5,
scoring="roc_auc"
)
print("Cross-Validation Accuracy per Fold Support Vector Machine:")
print(cv_scores_svm)

Cross-Validation Accuracy per Fold Support Vector Machine:
[0.99843337 0.99858675 0.99850851 0.99876648 0.99887759]

In [18]:
print("Average Cross-Validation Accuracy for Support Vector Machine:")
print(cv_scores_svm.mean())

Average Cross-Validation Accuracy for Support Vector Machine:
0.9986345398152178

In [19]:
from sklearn.metrics import confusion_matrix
cmSVM = confusion_matrix(y_test, y_pred_svm)
confusionSVM = pd.DataFrame(cmSVM, index=dataPipelineSVM.classes_, columns=dataPipelineSVM.classes_)
print(confusionSVM)

       0      1
0  20015    174
1      0  26970

In [20]:
# Derive honest rates from the confusion matrix (rows=true, cols=pred)
tn, fp, fn, tp = cmSVM.ravel()
print(f"Recall on class-0: {tn/(tn+fp):.4f}")
print(f"Recall on class-1: {tp/(tp+fn):.4f}")

Recall on class-0: 0.9914
Recall on class-1: 1.0000

In [21]:
from sklearn.metrics import classification_report
y_predSVM = dataPipelineSVM.predict(X_test)
print("Classification Report - Support Vector Machine")
print(classification_report(y_test, y_predSVM))

Classification Report - Support Vector Machine
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     20189
           1       0.99      1.00      1.00     26970

    accuracy                           1.00     47159
   macro avg       1.00      1.00      1.00     47159
weighted avg       1.00      1.00      1.00     47159

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Extract the coefficients from the trained LinearSVC model
coefs = dataPipelineSVM.named_steps['classifier'].coef_[0]
features = URL_ONLY_FEATURES

# Create a DataFrame to easily view and sort features by their coefficient magnitudes
coef_df = pd.DataFrame({
    'Feature': features,
    'Coefficient': coefs,
    'Absolute_Coefficient': np.abs(coefs)
}).sort_values(by='Absolute_Coefficient', ascending=False)

print("Feature Coefficients (Sorted by Importance/Magnitude):")
display(coef_df)

Feature Coefficients (Sorted by Importance/Magnitude):

                       Feature  Coefficient  Absolute_Coefficient
8             NoOfLettersInURL    -8.931531              8.931531
10             NoOfDegitsInURL    -4.146055              4.146055
1                 DomainLength     3.756918              3.756918
0                    URLLength    -2.574102              2.574102
15  NoOfOtherSpecialCharsInURL    -2.477989              2.477989
17                     IsHTTPS     1.027102              1.027102
12             NoOfEqualsInURL     0.276775              0.276775
11             DegitRatioInURL    -0.239985              0.239985
16       SpacialCharRatioInURL     0.202746              0.202746
14          NoOfAmpersandInURL     0.184629              0.184629
9             LetterRatioInURL    -0.181704              0.181704
5               HasObfuscation     0.142273              0.142273
2                   IsDomainIP     0.138741              0.138741
6           NoOfObfuscatedChar     0.110993              0.110993
13              NoOfQMarkInURL    -0.055325              0.055325
3                    TLDLength    -0.036446              0.036446
4                NoOfSubDomain     0.010766              0.010766
7             ObfuscationRatio    -0.005312              0.005312

In [23]:
# Check correlation of these features with the target variable directly
train_df = X_train.copy()
train_df['label'] = y_train
correlations = train_df.corr()['label'].sort_values(ascending=False)

print("Correlation of Features with the Target Class (label):")
display(correlations)

Correlation of Features with the Target Class (label):

label                         1.000000
IsHTTPS                       0.609105
NoOfSubDomain                -0.007363
NoOfObfuscatedChar           -0.014840
NoOfAmpersandInURL           -0.033367
ObfuscationRatio             -0.041517
HasObfuscation               -0.052269
IsDomainIP                   -0.061118
NoOfEqualsInURL              -0.073157
TLDLength                    -0.079727
NoOfDegitsInURL              -0.168959
NoOfQMarkInURL               -0.176009
URLLength                    -0.235931
NoOfLettersInURL             -0.270140
DomainLength                 -0.284402
NoOfOtherSpecialCharsInURL   -0.345218
LetterRatioInURL             -0.368522
DegitRatioInURL              -0.432309
SpacialCharRatioInURL        -0.533748
Name: label, dtype: float64

In [24]:
from sklearn.model_selection import GroupKFold
gkf = GroupKFold(n_splits=5)
groups = data["Domain"].values
for fold, (tr, te) in enumerate(gkf.split(X, y, groups)):
    m = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler()),
        ('clf', LinearSVC(max_iter=20000, C=0.1, random_state=42, dual="auto")),
    ])
    m.fit(X.iloc[tr], y.iloc[tr])
    acc = m.score(X.iloc[te], y.iloc[te])
    print(f"Fold {fold}: group-split accuracy = {acc:.4f}")

Fold 0: group-split accuracy = 0.9965
Fold 1: group-split accuracy = 0.9964
Fold 2: group-split accuracy = 0.9960
Fold 3: group-split accuracy = 0.9961
Fold 4: group-split accuracy = 0.9966

In [25]:
def extract_url_features_csv_compatible(url: str) -> dict:
    import re
    from urllib.parse import urlparse

    u = url.strip()

    # URLLength: strip scheme, replace https with http
    normalized = u.replace("https://", "http://", 1) if u.startswith("https://") else u
    url_len = len(normalized)

    # Parse host
    parse_target = u if "://" in u else "http://" + u
    host = urlparse(parse_target).netloc.split("@")[-1].split(":")[0].lower()
    parts = host.split(".")
    tld = parts[-1] if len(parts) >= 2 else ""

    # DomainLength: length of full host (matches CSV)
    domain_len = len(host)

    # IsDomainIP: strict IP check
    import ipaddress
    try:
        ipaddress.ip_address(host)
        is_ip = 1
    except ValueError:
        is_ip = 0

    # NoOfSubDomain: number of dots - 1 (floored at 0)
    no_sub = max(0, host.count(".") - 1)

    # Obfuscation: same as before (%XX)
    obf_chars = len(re.findall(r"%[0-9A-Fa-f]{2}", u))
    has_obf = int(obf_chars > 0)
    obf_ratio = obf_chars / max(1, url_len)

    # CRITICAL: host without "www." prefix
    host_wo_www = host[4:] if host.startswith("www.") else host

    # NoOfLettersInURL = letters in host_wo_www[:-1]
    # (The -1 reproduces the CSV's off-by-one; may be a bug in the original code)
    sld_and_tld = host_wo_www[:-1]
    n_letters = sum(c.isalpha() for c in sld_and_tld)

    # NoOfDegitsInURL = digits in full URL? or in host_wo_www?
    # From samples, all had 0 digits, can't distinguish. Use host_wo_www to be safe.
    n_digits = sum(c.isdigit() for c in host_wo_www)

    # NoOfOtherSpecialCharsInURL = specials in host_wo_www[:-1]
    n_other_special = sum(1 for c in sld_and_tld if not c.isalnum())

    # From CSV ratios:
    # LetterRatioInURL = n_letters / url_len
    # For voicefmradio: 15 / 29 = 0.517 ✅
    # DegitRatioInURL = n_digits / url_len
    # SpacialCharRatioInURL = n_other_special / url_len
    # For southbank: 1 / 31 = 0.032 ✅
    # For voicefmradio: 2 / 29 = 0.069 ✅
    # For uni-mainz: 2 / 23 = 0.087 ✅

    return {
        "URLLength": float(url_len),
        "DomainLength": float(domain_len),
        "IsDomainIP": float(is_ip),
        "TLDLength": float(len(tld)),
        "NoOfSubDomain": float(no_sub),
        "HasObfuscation": float(has_obf),
        "NoOfObfuscatedChar": float(obf_chars),
        "ObfuscationRatio": round(obf_ratio, 3),
        "NoOfLettersInURL": float(n_letters),
        "LetterRatioInURL": round(n_letters / max(1, url_len), 3),
        "NoOfDegitsInURL": float(n_digits),
        "DegitRatioInURL": round(n_digits / max(1, url_len), 3),
        "NoOfEqualsInURL": float(u.count("=")),
        "NoOfQMarkInURL": float(u.count("?")),
        "NoOfAmpersandInURL": float(u.count("&")),
        "NoOfOtherSpecialCharsInURL": float(n_other_special),
        "SpacialCharRatioInURL": round(n_other_special / max(1, url_len), 3),
        "IsHTTPS": float(u.lower().startswith("https://")),
    }

In [47]:
url = "https://www.youtube.com"

In [48]:
# Extract and print URL features
features = extract_url_features_csv_compatible(url)

for key, value in features.items():
    print(f"{key}: {value}")

URLLength: 22.0
DomainLength: 15.0
IsDomainIP: 0.0
TLDLength: 3.0
NoOfSubDomain: 1.0
HasObfuscation: 0.0
NoOfObfuscatedChar: 0.0
ObfuscationRatio: 0.0
NoOfLettersInURL: 9.0
LetterRatioInURL: 0.409
NoOfDegitsInURL: 0.0
DegitRatioInURL: 0.0
NoOfEqualsInURL: 0.0
NoOfQMarkInURL: 0.0
NoOfAmpersandInURL: 0.0
NoOfOtherSpecialCharsInURL: 1.0
SpacialCharRatioInURL: 0.045
IsHTTPS: 1.0

In [49]:
# Convert the extracted features dictionary into a DataFrame with a single row
# using the exact features and order used during training (URL_ONLY_FEATURES)
features_df = pd.DataFrame([features])[URL_ONLY_FEATURES]

# Run prediction using our trained pipeline
prediction = dataPipelineSVM.predict(features_df)[0]

# Display the results
print(f"URL: {url}")
print(f"Predicted Label: {prediction} ({'Phishing' if prediction == 0 else 'Legitimate'})")

URL: https://www.youtube.com
Predicted Label: 1 (Legitimate)

In [29]:
# Select a few rows from the original data to compare
sample_data = data.dropna(subset=['URL']).head(3)

for idx, row in sample_data.iterrows():
    sample_url = row['URL']
    extracted = extract_url_features_csv_compatible(sample_url)

    print(f"\n--- Comparing URL: {sample_url} ---")
    comparison_records = []
    for feature_name in URL_ONLY_FEATURES:
        csv_val = row[feature_name]
        ext_val = extracted[feature_name]
        status = "MATCH" if csv_val == ext_val else "MISMATCH"
        comparison_records.append({
            "Feature": feature_name,
            "CSV Value": csv_val,
            "Extracted Value": ext_val,
            "Status": status
        })
    display(pd.DataFrame(comparison_records))

--- Comparing URL: https://www.southbankmosaics.com ---

                       Feature  CSV Value  Extracted Value Status
0                    URLLength     31.000           31.000  MATCH
1                 DomainLength     24.000           24.000  MATCH
2                   IsDomainIP      0.000            0.000  MATCH
3                    TLDLength      3.000            3.000  MATCH
4                NoOfSubDomain      1.000            1.000  MATCH
5               HasObfuscation      0.000            0.000  MATCH
6           NoOfObfuscatedChar      0.000            0.000  MATCH
7             ObfuscationRatio      0.000            0.000  MATCH
8             NoOfLettersInURL     18.000           18.000  MATCH
9             LetterRatioInURL      0.581            0.581  MATCH
10             NoOfDegitsInURL      0.000            0.000  MATCH
11             DegitRatioInURL      0.000            0.000  MATCH
12             NoOfEqualsInURL      0.000            0.000  MATCH
13              NoOfQMarkInURL      0.000            0.000  MATCH
14          NoOfAmpersandInURL      0.000            0.000  MATCH
15  NoOfOtherSpecialCharsInURL      1.000            1.000  MATCH
16       SpacialCharRatioInURL      0.032            0.032  MATCH
17                     IsHTTPS      1.000            1.000  MATCH

--- Comparing URL: https://www.uni-mainz.de ---

                       Feature  CSV Value  Extracted Value Status
0                    URLLength     23.000           23.000  MATCH
1                 DomainLength     16.000           16.000  MATCH
2                   IsDomainIP      0.000            0.000  MATCH
3                    TLDLength      2.000            2.000  MATCH
4                NoOfSubDomain      1.000            1.000  MATCH
5               HasObfuscation      0.000            0.000  MATCH
6           NoOfObfuscatedChar      0.000            0.000  MATCH
7             ObfuscationRatio      0.000            0.000  MATCH
8             NoOfLettersInURL      9.000            9.000  MATCH
9             LetterRatioInURL      0.391            0.391  MATCH
10             NoOfDegitsInURL      0.000            0.000  MATCH
11             DegitRatioInURL      0.000            0.000  MATCH
12             NoOfEqualsInURL      0.000            0.000  MATCH
13              NoOfQMarkInURL      0.000            0.000  MATCH
14          NoOfAmpersandInURL      0.000            0.000  MATCH
15  NoOfOtherSpecialCharsInURL      2.000            2.000  MATCH
16       SpacialCharRatioInURL      0.087            0.087  MATCH
17                     IsHTTPS      1.000            1.000  MATCH

--- Comparing URL: https://www.voicefmradio.co.uk ---

                       Feature  CSV Value  Extracted Value Status
0                    URLLength     29.000           29.000  MATCH
1                 DomainLength     22.000           22.000  MATCH
2                   IsDomainIP      0.000            0.000  MATCH
3                    TLDLength      2.000            2.000  MATCH
4                NoOfSubDomain      2.000            2.000  MATCH
5               HasObfuscation      0.000            0.000  MATCH
6           NoOfObfuscatedChar      0.000            0.000  MATCH
7             ObfuscationRatio      0.000            0.000  MATCH
8             NoOfLettersInURL     15.000           15.000  MATCH
9             LetterRatioInURL      0.517            0.517  MATCH
10             NoOfDegitsInURL      0.000            0.000  MATCH
11             DegitRatioInURL      0.000            0.000  MATCH
12             NoOfEqualsInURL      0.000            0.000  MATCH
13              NoOfQMarkInURL      0.000            0.000  MATCH
14          NoOfAmpersandInURL      0.000            0.000  MATCH
15  NoOfOtherSpecialCharsInURL      2.000            2.000  MATCH
16       SpacialCharRatioInURL      0.069            0.069  MATCH
17                     IsHTTPS      1.000            1.000  MATCH

In [ ]:
import joblib

joblib.dump(dataPipelineSVM, "phishing_model.joblib")

In [ ]:
joblib.dump(URL_ONLY_FEATURES, "url_features.joblib")